version: '3.1'

services:
  mongo:
    image: mongo
    container_name: webpoint
    ports:  # for demo/debug purpose only
      - 27017:27017
    #volumes:
    #  - $HOME/data/mongo:/data/db
    #  - $HOME/data/mongo:/data/bkp
    restart: always
    environment:
      MONGODB_APPLICATION_DATABASE: webpoint-dev
#      MONGODB_APPLICATION_USER: $MONGODB_APPLICATION_USER
#      MONGODB_APPLICATION_PASS: $MONGODB_APPLICATION_PASS
#      MONGODB_ADMIN_USER: $MONGODB_ADMIN_USER
#      MONGODB_ADMIN_PASS: $MONGODB_ADMIN_PASS