---
environments:
   development:
      grails:
         mongodb:
            host: "localhost"
            port: 27017
            databaseName: "webpoint-dev"
   test:
      grails:
         mongodb:
            dbCreate: "update"
            host: "localhost"
            port: 27017
            databaseName: "webpoint-test"
   production:
      grails:
         mongodb:
            host: "localhost"
            port: 27017
            databaseName: "webpoint-prod"
---

grails:
    gorm:
        failOnError: true
---
grails:
    profile: angular
    codegen:
        defaultPackage: webpoint3
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
---
grails:
    controllers:
        upload:
            maxFileSize: 10000000
            maxRequestSize: 10000000