---
environments:
   development:
      grails:
         mongodb:
            host: "localhost"
            port: 27017
            databaseName: "webpoint-dev"
   test:
      grails:
         mongodb:
            dbCreate: "update"
            host: "localhost"
            port: 27017
            databaseName: "webpoint-test"
   production:
      grails:
         mongodb:
            host: "${MONGO_WEBPOINT_HOST}"
            port: 27017
            username: "${MONGO_WEBPOINT_USER}"
            password: "${MONGO_WEBPOINT_PASS}"
            databaseName: "webpoint-prod"

---
grails:
    profile: angular
    codegen:
        defaultPackage: webpoint3
    spring:
        transactionManagement:
            proxies: false
    gorm:
        failOnError: true
#        autowire: false
    databinding:
        trimStrings: false                  # the default value is true
        convertEmptyStringsToNull: true     # the default value is true
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 10000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 15000000
            maxRequestSize: 12000000
    converters:
        encoding: UTF-8
---
twitter:
  routing:
    consumerkey: "${TWITTER_CONSUMER_KEY}"
    consumersecret: "${TWITTER_CONSUMER_SECRET}"
    oauth:
      accesstoken: "${TWITTER_ACCESS_TOKEN}"
      accesstokensecret: "${TWITTER_ACCESS_TOKEN_SECRET}"
---
# YOUR_MAX_SIZE_IN_MB * 1024 * 1024 = BYTES
#server:
#    port: 8443                                             # The port to listen on
#    ssl:
#        enabled: true                                      # Activate HTTPS mode on the server port
#        key-store: <the-location-of-your-keystore>         # e.g. /etc/tomcat7/keystore/tomcat.keystore
#        key-store-password: <your-key-store-password>      # e.g. changeit
#        key-alias: <your-key-alias>                        # e.g. tomcat
#        key-password: <usually-the-same-as-your-key-store-password>